### ISSUE TITLE
License Needed

### ISSUE THREAD

**Issue by carceneaux** [bryansullins/baremetalesxi#1]
Hi Bryan,

I thoroughly enjoyed your session at the Indy UserCon yesterday. IMO, best session of the day. 😄 

Can you please [choose a license](https://choosealicense.com/) for this project and add it? Without a license, no one is _supposed_ to use your code in this project in any capacity. FWIW, I normally use [MIT](https://choosealicense.com/licenses/mit/).

Thanks again!
Chris

**Comment by bryansullins** [comment]
Thanks, Chris, I just saw this. Much appreciated - that is true!

**Comment by mariolenz** [comment]
@bryansullins @carceneaux Since a license has been added in the meantime, don't you think this issue should be closed? Just a thought... ;-)

**Comment by bryansullins** [comment]
Yes - thank you!
