### ISSUE TITLE
NGINX configuration file 

### ISSUE THREAD

**Issue by amieltahir** [bryansullins/baremetalesxi#3]
Hi Brian,

We are attempting to use this recipe to provision HPE Gen8 with single touch, so far the playbook is working and the generated ISO at NGINX webserver is being mounted at ilo but it can't boot.  We tested the manual booting for the same original ISO and it works.

Can you please share the NGINX configuration you have used. Maybe there is some special conf to be added - in my conf file the mime type is added 

default_type        application/octet-stream;

Attached is nginx.conf

Thanks in advance
Ahmed 
[nginx.conf.txt](https://github.com/bryansullins/baremetalesxi/files/9121550/nginx.conf.txt)

**Comment by bryansullins** [comment]
Ah. The machine I used for this is now long gone. If I recall it was mostly defaults, and from memory, I don't recall having to change anything.

I am not seeing any red flags in your config. If you have logs you can send me I can look them over.

Also, the usual issues are:

1. Lack of connectivity from the target server to the web server. Try mounting this manually.
2. Wrong type of iso boot connection specified in the code (unlikely).
3. Incorrect permissions on the www directory on the web server.

**Comment by amieltahir** [comment]
Thanks a million Bryan, it turns out I needed to add a firewall rule for port 8080 on the server and now it works.

We can boot the server and install ESXi 

However its failing at this task, is there a way to change no_log behaviour to actually display errors for this VMware collection.

## vCenter and ESXi configuration follows here:
  - name: Adding ESXi host "{{ esxi_hostname }}.ictms.lab" to vCenter . . .
    vmware_host:
      hostname: "{{ vcenter_hostname }}"
      username: "svc_VMW_Ansible"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      #cluster_name: "{{ cluster_name }}"
      esxi_hostname: "{{ esxi_hostname }}.ictms.lab"
      esxi_username: "root"
      esxi_password: "{{ esxi_password }}"
      state: present
      validate_certs: false
    delegate_to: localhost



TASK [Adding ESXi host "esxi01-mgmt-aet.ictms.lab" to vCenter . . .] ***************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

Here is my Ansible environment, I can install ssl manually from pypi but i dont see packages for hashlib, socket 

(ansible3.0) [root@lsgmsauto baremetalesxi]# pip3 list
Package                            Version
---------------------------------- -----------
ansible                            3.0.0
ansible-base                       2.10.17
certifi                            2022.5.18.1
cffi                               1.15.0
chardet                            4.0.0
charset-normalizer                 2.0.12
cryptography                       37.0.2
idna                               3.3
Jinja2                             3.0.3
lxml                               4.9.0
MarkupSafe                         2.0.1
nsx-policy-python-sdk              3.1.5.0.0
nsx-python-sdk                     3.1.5.0.0
nsx-vmc-aws-integration-python-sdk 3.1.5.0.0
nsx-vmc-policy-python-sdk          3.1.5.0.0
packaging                          21.3
pip                                21.3.1
pycparser                          2.21
pyOpenSSL                          22.0.0
pyparsing                          3.0.9
python-hpilo                       4.4.3
pyvmomi                            7.0.3
PyYAML                             6.0
requests                           2.27.1
setuptools                         39.2.0
six                                1.16.0
urllib3                            1.26.9
vapi-client-bindings               3.8.0
vapi-common-client                 2.34.0
vapi-runtime                       2.34.0
vmc-client-bindings                1.59.0
vmc-draas-client-bindings          1.19.0
vSphere-Automation-SDK             1.77.0



Thanks in advance,

**Comment by amieltahir** [comment]
Thanks Bryan i can see the errors now with no_log: false

I also added firewall rule for port 8080 now the server is booting from the playbook.

**Comment by amieltahir** [comment]
TASK [Adding ESXi host "esxi01-mgmt-aet.ictms.lab" to vCenter . . .] ***************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unable to log on to vCenter or ESXi API at IP_address:443  as svc_VMW_Ansible: Cannot complete login due to an incorrect user name or password."

The new installed ESXi can be pinged but i can't see it on the browser with https://IP_address 

I believe the rest of playbook will work when the ESXi is able to be loaded on the browser.

Any thoughts?
Ahmed

**Comment by bryansullins** [comment]
Excellent! Glad you were successful!
