### ISSUE TITLE
Missing files from repo?

### ISSUE THREAD

**Issue by AlmostANinja** [bryansullins/baremetalesxi#4]
Hi there,

I am very interested in this ansible deployment you put together,  however (and please forgive my stupidity as I am new to ansible), it seems there are a few files missing?

You mention a fullmetal.yml that contains esxi versions? Also I notice many variables that have not been defined anywhere. 

Would you mind including those in your repo please?

Thanks

**Comment by bryansullins** [comment]
Fixed. The README.md file had the wrong filename referenced (fullmetal.yml), so I changed it to match the correct filename in the repo (fullmetalbuild.yml). My apologies for the confusion!

Also, you are not stupid you are learning and that is awesome! Send me an email or comment if you need any help!

As far as the variables not being defined, you will need to fill those in for your environment, such as with the vars/vcentervars.yml file you would fill in the `vcenter_hostname: ""` with your vCenter hostname:

`vcenter_hostname: "your.vcenter.FQDN.or.IP.Address"`
