### ISSUE TITLE
Possible Issue with ESXi 7.0 and Virtual Switches

### ISSUE THREAD

**Issue by dgoldsmith** [bryansullins/baremetalesxi#5]
I am playing with your repo.  I've pulled out bits of the fullmetal.yml file to try (skipping the kickstart install for now).

In your task "Adding vmnic1 to vSwitch0", the array has a single parameter for vmnic1.   What I am experiencing is vmnic0 gets removed from the vSwitch and then I lose connectivity to the ESXi host.

If I make the array contain both vmnic0 and vmnic1, then vmnic1 gets added as a second uplink.

This is using vSphere ESXi 7.0 U3g (latest 7.x release)

Thanks,
David Goldsmith

**Comment by bryansullins** [comment]
Thanks David!

My apologies for taking so long, but here I am.

Can you tell me what version of Ansible you are using? I am assuming there are no errors, it just does all the things. Any verbosity you can give me with what it does for that yaml block would be helpful.

My current theory would be that a newer version of Ansible may require more explicit defined vmnics, or that version 7 may require some changes along those lines.
