### ISSUE TITLE
Any issues when first getting URL boot working

### ISSUE THREAD

**Issue by smitch35** [bryansullins/baremetalesxi#6]
I know this is a bit outside the scope of the repo but I'm just wondering if you ever had any issues when first getting the systems to boot off URL?  I've verified everything can talk and of course HP says the url path is good but I can not seem to get the hardware to boot off virtual URL.  Mounting just an ISO works ok though and we're able to use everyt thing else you've written really well.

Thanks

**Comment by bryansullins** [comment]
Thank you!

Main reason for not being able to run from the URL is permissions on the underlying web server. I used nginx.
