### ISSUE TITLE
Issue when calling against an inventory file

### ISSUE THREAD

**Issue by sferguson524** [bryansullins/baremetalesxi#7]
How would I modify this to run against an inventory file.  To create 17 hosts at a time for example?

**Comment by sferguson524** [comment]
When I run ansible-playbook -i ../inventories/37_dfw.yml fullmetalbuild.yml, I get:
"Failed to connect to the host via ssh: ssh: Could not resolve hostname

**Comment by bryansullins** [comment]
You will need to pre-populate the inventory file with the hostname your are building and ensure that the hostname is resolvable through DNS by the machine running the Ansible playbook, or you can have ansible be able to resolve it on the fly: [Hostnames in Ansible](https://stackoverflow.com/questions/47523162/getting-an-error-message-failed-to-connect-to-the-host-via-ssh-while-trying-to)
but the long term fix is to pre-populate in DNS.
